// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvtDFHCF26LhXw2t44N9fo6VKFJGNxCc',
    appId: '1:244266612114:web:041442e43eb096f004bd4b',
    messagingSenderId: '244266612114',
    projectId: 'gym-bay-beo',
    authDomain: 'gym-bay-beo.firebaseapp.com',
    storageBucket: 'gym-bay-beo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0W71_ON8EsJrg0Qca_kpVlj5tFOswEf4',
    appId: '1:244266612114:android:701c9c71f47ca6c704bd4b',
    messagingSenderId: '244266612114',
    projectId: 'gym-bay-beo',
    storageBucket: 'gym-bay-beo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiBrTIRnbpFQs65k55d8kRbdBD3yPJ_V0',
    appId: '1:244266612114:ios:5a19a934985fb4b304bd4b',
    messagingSenderId: '244266612114',
    projectId: 'gym-bay-beo',
    storageBucket: 'gym-bay-beo.firebasestorage.app',
    iosBundleId: 'com.example.gymBayBeo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiBrTIRnbpFQs65k55d8kRbdBD3yPJ_V0',
    appId: '1:244266612114:ios:5a19a934985fb4b304bd4b',
    messagingSenderId: '244266612114',
    projectId: 'gym-bay-beo',
    storageBucket: 'gym-bay-beo.firebasestorage.app',
    iosBundleId: 'com.example.gymBayBeo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBvtDFHCF26LhXw2t44N9fo6VKFJGNxCc',
    appId: '1:244266612114:web:4d1f2fea450a33dc04bd4b',
    messagingSenderId: '244266612114',
    projectId: 'gym-bay-beo',
    authDomain: 'gym-bay-beo.firebaseapp.com',
    storageBucket: 'gym-bay-beo.firebasestorage.app',
  );
}
